name: jie
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.20.3
  - pandas=1.3.4
  - scikit-learn=1.0.1
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - scipy=1.7.2
  - tqdm=4.62.3
  - python-igraph=0.9.6
